"""Initial migration

Revision ID: 6d4140ba1698
Revises: 
Create Date: 2026-02-08 17:24:34.173102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added missing import


# revision identifiers, used by Alembic.
revision: str = '6d4140ba1698'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationhistory',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversationhistory_user_id'), 'conversationhistory', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.add_column('task', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'due_date')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_conversationhistory_user_id'), table_name='conversationhistory')
    op.drop_table('conversationhistory')
    # ### end Alembic commands ###
